## Исключения

__try:__
 > отлавливаем ошибки \
 ... 
 
 __except__ NameError as e:
 > действия при перехвате ошибки NameError 
 ...
 
 > продолжаем нормальную работу

__else:__
>Дополнительные действия можно указать в блоке else.

Блок else не сработает, если внутри try произошло любое из событий:
* возбуждено исключение
* выполнена команда return
* выполнена команда break
* выполнена команда continue

__finally:__
> выполняется в любом случае